ERMS-4509
hbz/laser3 pull request #60
Opened 2022-10-27 09:50 UTC by Inselhopper

2022-10-27 10:01 UTC, klodav commented on grails-app/views/dev/_frontend_copyFunction.gsp
> +              data-position="top center" data-content="Klicke, um zu kopieren">
i18n

2022-10-27 10:02 UTC, klodav commented on grails-app/views/dev/_frontend_copyFunction.gsp
> +              data-position="top center" data-content="Klicke, um zu kopieren">
i18n

2022-10-27 10:02 UTC, klodav commented on grails-app/views/dev/_frontend_copyFunction.gsp
>                data-position="top center" data-content="Klicke, um zu kopieren">
i18n

2022-10-27 10:02 UTC, klodav commented on grails-app/views/dev/_frontend_copyFunction.gsp
>                            data-position="top center" data-content="Klicke, um zu kopieren">
i18n

2022-10-27 10:03 UTC, klodav commented on grails-app/views/templates/survey/_subscriptionSurvey.gsp
> +                                                             data-position="top center" data-content="Klicke, um zu kopieren">
i18n

2022-10-27 10:04 UTC, klodav commented on grails-app/views/templates/cpa/_contact.gsp
> +                <span class="la-popup-tooltip la-delay" data-position="top right" data-content="Diese URL aufrufen ..">
i18n

2022-10-27 10:04 UTC, klodav commented on grails-app/views/templates/cpa/_contact.gsp
> +                <span class="la-popup-tooltip la-delay" data-position="top right" data-content="Mail senden an ..">
i18n

2022-10-27 10:08 UTC, klodav requested changes
see above

2022-10-27 10:41 UTC, Inselhopper commented on grails-app/views/dev/_frontend_copyFunction.gsp
> +              data-position="top center" data-content="Klicke, um zu kopieren">
done

2022-11-02 06:01 UTC, klodav commented on grails-app/views/templates/meta/_identifierList.gsp
> +                            ääääää
???

2022-11-02 10:13 UTC, klodav approved these changes

2022-11-02 10:13 UTC, merged